apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  strategy: {}
  template:
    metadata:
      labels:
        app: myapp
    spec:
      initContainers:
        - image: busybox:latest
          name: sleep
          command: ["sh","-c","sleep 30"]
      containers:
      - image: MY_NEW_IMAGE
        name: sample-go-app
        lifecycle:
          preStop:
            exec:
              command: ["sh","-c","echo I'm deleted & sleep 5"]
        resources: {}
        livenessProbe:
          tcpSocket:
            port: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp
  namespace: myapp
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp
  type: ClusterIP